REM Hakker opp planomriss i landsdekkende, kommunevise og fylkesvise GML-filer i lokal UTM-sone  
"C:\Program Files\FME\fme.exe" \\nnrite507\Geodata\Jobs\NRL_postgis2gml\NRL_postgis2gml.fmw --FNR "1" --OUTPUT_EPSG_CODE "25832" --FANOUT "Fylker"
"C:\Program Files\FME\fme.exe" \\nnrite507\Geodata\Jobs\NRL_postgis2gml\NRL_postgis2gml.fmw --FNR "2" --OUTPUT_EPSG_CODE "25832" --FANOUT "Fylker"
"C:\Program Files\FME\fme.exe" \\nnrite507\Geodata\Jobs\NRL_postgis2gml\NRL_postgis2gml.fmw --FNR "3" --OUTPUT_EPSG_CODE "25832" --FANOUT "Fylker"
"C:\Program Files\FME\fme.exe" \\nnrite507\Geodata\Jobs\NRL_postgis2gml\NRL_postgis2gml.fmw --FNR "4" --OUTPUT_EPSG_CODE "25832" --FANOUT "Fylker"
"C:\Program Files\FME\fme.exe" \\nnrite507\Geodata\Jobs\NRL_postgis2gml\NRL_postgis2gml.fmw --FNR "5" --OUTPUT_EPSG_CODE "25832" --FANOUT "Fylker"
"C:\Program Files\FME\fme.exe" \\nnrite507\Geodata\Jobs\NRL_postgis2gml\NRL_postgis2gml.fmw --FNR "6" --OUTPUT_EPSG_CODE "25832" --FANOUT "Fylker"
"C:\Program Files\FME\fme.exe" \\nnrite507\Geodata\Jobs\NRL_postgis2gml\NRL_postgis2gml.fmw --FNR "7" --OUTPUT_EPSG_CODE "25832" --FANOUT "Fylker"
"C:\Program Files\FME\fme.exe" \\nnrite507\Geodata\Jobs\NRL_postgis2gml\NRL_postgis2gml.fmw --FNR "8" --OUTPUT_EPSG_CODE "25832" --FANOUT "Fylker"
"C:\Program Files\FME\fme.exe" \\nnrite507\Geodata\Jobs\NRL_postgis2gml\NRL_postgis2gml.fmw --FNR "9" --OUTPUT_EPSG_CODE "25832" --FANOUT "Fylker"
"C:\Program Files\FME\fme.exe" \\nnrite507\Geodata\Jobs\NRL_postgis2gml\NRL_postgis2gml.fmw --FNR "10" --OUTPUT_EPSG_CODE "25832" --FANOUT "Fylker"
"C:\Program Files\FME\fme.exe" \\nnrite507\Geodata\Jobs\NRL_postgis2gml\NRL_postgis2gml.fmw --FNR "14" --OUTPUT_EPSG_CODE "25832" --FANOUT "Fylker"
"C:\Program Files\FME\fme.exe" \\nnrite507\Geodata\Jobs\NRL_postgis2gml\NRL_postgis2gml.fmw --FNR "15" --OUTPUT_EPSG_CODE "25832" --FANOUT "Fylker"
"C:\Program Files\FME\fme.exe" \\nnrite507\Geodata\Jobs\NRL_postgis2gml\NRL_postgis2gml.fmw --FNR "16" --OUTPUT_EPSG_CODE "25832" --FANOUT "Fylker"
"C:\Program Files\FME\fme.exe" \\nnrite507\Geodata\Jobs\NRL_postgis2gml\NRL_postgis2gml.fmw --FNR "17" --OUTPUT_EPSG_CODE "25832" --FANOUT "Fylker"
"C:\Program Files\FME\fme.exe" \\nnrite507\Geodata\Jobs\NRL_postgis2gml\NRL_postgis2gml.fmw --FNR "18" --OUTPUT_EPSG_CODE "25833" --FANOUT "Fylker"
"C:\Program Files\FME\fme.exe" \\nnrite507\Geodata\Jobs\NRL_postgis2gml\NRL_postgis2gml.fmw --FNR "19" --OUTPUT_EPSG_CODE "25833" --FANOUT "Fylker"
"C:\Program Files\FME\fme.exe" \\nnrite507\Geodata\Jobs\NRL_postgis2gml\NRL_postgis2gml.fmw --FNR "20" --OUTPUT_EPSG_CODE "25835" --FANOUT "Fylker"
"C:\Program Files\FME\fme.exe" \\nnrite507\Geodata\Jobs\NRL_postgis2gml\NRL_postgis2gml.fmw --OUTPUT_EPSG_CODE "25833"
