create or replace view nrl.v_vertikalobjektkomponentpunkt as 
select vertikalobjektkomponentpunkt.objid as vok_objid,
  vertikalobjekt.objid as vo_objid,
  vertikalobjektkomponentpunkt.objtype as vok_objtype,
  vertikalobjekt.objtype as vo_objtype,
  vertikalobjekt.kommentarvertobjtype as kommentarvertobjtype,
  vertikalobjekt.vertikalobjektgruppe as vertikalobjektgruppe,
  vertikalobjekt.vertikalobjektnavn as vertikalobjektnavn,
  vertikalobjekt.vertikalobjekttype as vertikalobjekttype,
  vertikalobjekt.datafangstdato as datafangstdato,
  vertikalobjekt.typeendring as vo_typeendring,
  vertikalobjekt.endret_tid as vo_endret_tid,
  vertikalobjekt.gyldigfra as gyldigfra,
  vertikalobjekt.gyldigtil as gyldigtil,
  vertikalobjekt.lokalid as vo_lokalid,
  vertikalobjekt.navnerom as vo_navnerom,
  vertikalobjekt.versjonid as vo_versjonsid,
  vertikalobjekt.informasjon as informasjon,
  vertikalobjekt.oppdateringsdato as vo_oppdateringsdato,
  vertikalobjekt.opphav as opphav,
  vertikalobjekt.status as vo_status,
  vertikalobjektkomponentpunkt.brekkbar as brekkbar,
  vertikalobjektkomponentpunkt.vertikalutstrekning as vertikalutstrekning,
  vertikalobjektkomponentpunkt.hoydeverdienhet as hoydeverdienhet,
  vertikalobjektkomponentpunkt.merkepliktig as merkepliktig,
  vertikalobjektkomponentpunkt.merkepliktigihenholdtil as merkepliktigihenholdtil,
  vertikalobjektkomponentpunkt.ansvarligformerking as ansvarligformerking,
  vertikalobjektkomponentpunkt.merkeinformasjon as merkeinformasjon,
  vertikalobjektkomponentpunkt.kommentarmerkeplikt as kommentarmerkeplikt,
  vertikalobjektkomponentpunkt.hrefsystem as hrefsystem,
  vertikalobjektkomponentpunkt.href as href,
  vertikalobjektkomponentpunkt.registernavn as registernavn,
  vertikalobjektkomponentpunkt.eksternid as eksternid,
  vertikalobjektkomponentpunkt.mobilitet as mobilitet,
  vertikalobjektkomponentpunkt.komponentsekvnr as komponentsekvnr,
  vertikalobjektkomponentpunkt.bsle21hinder as bsle21hinder,
  vertikalobjektkomponentpunkt.lokalid as vok_lokalid,
  vertikalobjektkomponentpunkt.navnerom as vok_navnerom,
  vertikalobjektkomponentpunkt.versjonid as vok_versjonid,
  vertikalobjektkomponentpunkt.verifiseringsdato as verifiseringsdato,
  vertikalobjektkomponentpunkt.oppdateringsdato as vok_oppdateringsdato,
  vertikalobjektkomponentpunkt.malemetode as malemetode,
  vertikalobjektkomponentpunkt.noyaktighet as noyaktighet,
  vertikalobjektkomponentpunkt.synbarhet as synbarhet,
  vertikalobjektkomponentpunkt.malemetodehoyde as malemetodehoyde,
  vertikalobjektkomponentpunkt.h_noyaktighet as h_noyaktighet,
  vertikalobjektkomponentpunkt.typeendring as vok_typeendring,
  vertikalobjektkomponentpunkt.endret_tid as vok_endret_tid,
  vertikalobjektkomponentpunkt.status as vok_status,
  lyssetting.lystype as lystype,
  vertikalobjektkomponentpunkt.posisjon as posisjon
from nrl.vertikalobjektkomponentpunkt
left outer join nrl.vertikalobjekt
  on vertikalobjekt.objid = vertikalobjektkomponentpunkt.bestaravvertikalobjektkomponentfk
left outer join nrl.lyssetting
  on vertikalobjektkomponentpunkt.objid = lyssetting.harlyssettingfk;