CREATE OR REPLACE VIEW korallrev.v_sp_korallrev AS
SELECT rev.objid               as objid,
       rev.objtype             as objtype, 
       rev.obs_metode          as obs_metode, 
       rev.obs_start           as obs_start, 
       rev.obs_slutt           as obs_slutt, 
       rev.bmnatyp             as bmnatyp, 
       rev.bm_kildenavn        as bm_kildenavn, 
       rev.bm_kildetittel      as bm_kildetittel, 
       rev.bmkildtyp           as bmkildtyp, 
       rev.bm_kildeaar         as bm_kildeaar, 
       rev.dybde_min           as dybde_min, 
       rev.dybde_max           as dybde_max, 
       rev.posisjon            as posisjon, 
       rev.lokalid             as lokalid, 
       rev.navnerom            as navnerom, 
       rev.versjonid           as versjonid, 
       rev.verifiseringsdato   as verifiseringsdato, 
       rev.maalemetode         as maalemetode, 
       rev.noeyaktighet        as noeyaktighet, 
       rev.synbarhet           as synbarhet, 
       rev.maalemetodehoeyde   as maalemetodehoeyde, 
       rev.h_noeyaktighet      as h_noeyaktighet, 
       rev.max_avvik           as max_avvik, 
       rev.medium              as medium,
       rev.opphav              as opphav, 
       rev.noeyaktighetsklasse as noeyaktighetsklasse, 
       rev.produkt             as produkt,
       rev.versjon             as versjon,
       komm.navn               as k_navn,
       komm.kommuneid          as k_id,
       fylke.navn              as f_navn,
       fylke.fylkeid           as f_id
  FROM korallrev.korallrev rev,
       admingrense.fylkeflate fylke,
       admingrense.kommuneflate komm
 WHERE st_Intersects(komm.geom, rev.posisjon)
   AND ST_Intersects(fylke.geom, rev.posisjon);
   
CREATE OR REPLACE VIEW korallrev.v_korallrev AS
SELECT objid,
       objtype, 
       obs_metode, 
       obs_start, 
       obs_slutt, 
       bmnatyp, 
       bm_kildenavn, 
       bm_kildetittel, 
       bmkildtyp, 
       bm_kildeaar, 
       dybde_min, 
       dybde_max, 
       posisjon, 
       lokalid, 
       navnerom, 
       versjonid, 
       verifiseringsdato, 
       maalemetode, 
       noeyaktighet, 
       synbarhet, 
       maalemetodehoeyde, 
       h_noeyaktighet, 
       max_avvik, 
       medium,
       opphav, 
       noeyaktighetsklasse, 
       produkt,
       versjon,
       k_navn,
       k_id,
       f_navn,
       f_id
  FROM korallrev.v_sp_korallrev
UNION
SELECT objid,
       objtype, 
       obs_metode, 
       obs_start, 
       obs_slutt, 
       bmnatyp, 
       bm_kildenavn, 
       bm_kildetittel, 
       bmkildtyp, 
       bm_kildeaar, 
       dybde_min, 
       dybde_max, 
       posisjon, 
       lokalid, 
       navnerom, 
       versjonid, 
       verifiseringsdato, 
       maalemetode, 
       noeyaktighet, 
       synbarhet, 
       maalemetodehoeyde, 
       h_noeyaktighet, 
       max_avvik, 
       medium,
       opphav, 
       noeyaktighetsklasse, 
       produkt,
       versjon,
       'Uplassert-i-kommune'  as k_navn,
       9999                   as k_id,
       'Uplassert-i-fylke'    as f_navn,
       99                     as f_id
  FROM korallrev.korallrev
 WHERE objid not in (select objid from korallrev.v_sp_korallrev);
 